### ISSUE TITLE
After pip installing it, I can't import neither bitcoin, nor pybitcointools

### ISSUE THREAD

**Issue by sevandija** [vbuterin/pybitcointools#153]
Python 3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> from pybitcointools import *
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from pybitcointools import *
  File "C:\Users\Pig\Anaconda3\lib\site-packages\pybitcointools\__init__.py", line 1, in <module>
    from main import *
ModuleNotFoundError: No module named 'main'

>>> from bitcoin import *
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    from bitcoin import *
ModuleNotFoundError: No module named 'bitcoin'
>>>

**Comment by mtasic85** [comment]
Try to install using:

`pip install git+https://github.com/vbuterin/pybitcointools`

**Comment by kapilmar** [comment]
Worked for me with this:-

`pip install bitcoin`

**Comment by anurag0126** [comment]
pip install bitcoin

Worked for me as well

**Comment by antiNeuron** [comment]
The pip installation didn't work on my machine (Ubuntu 16.4) as I switched from python2 to 3. 
So, I just cloned the repo:
`git clone https://github.com/antiNeuron/pybitcointools.git`(I used one that I forked a while)
run setup.py:
`python3 setup.py install`

`from bitcoin import *` worked this time!

**Comment by mtasic85** [comment]
It is end of life for **pybitcointools** as author has stated in last commit.

However, if you manually clone code from this commit: https://github.com/vbuterin/pybitcointools/tree/aeb0a2bbb8bbfe421432d776c649650eaeb882a5

You will be able to install version that was working before.

**Comment by MagentoExp** [comment]
pip install bitcoin , worked for me ..!!!

**Comment by paulfioravanti** [comment]
After I started getting the errors mentioned, I found I had to re-install Pybitcointools using `pip`, pointing it at the last commit hash before the repository was deleted:

```
pip install git+https://github.com/vbuterin/pybitcointools.git@aeb0a2bbb8bbfe421432d776c649650eaeb882a5
```

**Comment by robermann** [comment]
I resolved my issues forking the project (into https://github.com/robermann/pybitcointools) and changing its module name: from 'bitcoin' to 'pybitcointools'.

If you want to give it a try: 
_pip install git+https://github.com/robermann/pybitcointools_

My _pip freeze_:
        bitcoin==1.1.42
        pybitcointools==1.1.42     (installed as above)
        python-bitcoinlib==0.10.1

**Comment by squarewave24** [comment]
i tried installing using methods here and the install succeeded, however when i try to run a simple example:

```
import pybitcointools
privkey = pybitcointools.random_key()
```
i get: 
> File "/Users/x/venv/lib/python3.6/site-packages/pybitcointools/__init__.py", line 1, in <module>
    from main import *
ModuleNotFoundError: No module named 'main'

**Comment by vv01f** [comment]
simply 
* install bitcoin via pip as stated above
* replace `pybitcointools` with `bitcoin` in your code
…works for me.
