### ISSUE TITLE
TypeError: privkey_to_pubkey() takes exactly 1 argument (0 given) get this error on running vitalik tutorial

### ISSUE THREAD

**Issue by markmark1** [vbuterin/pybitcointools#166]
k1=`pybtctool random_key`> k2=`pybtctool random_key`> k3=`pybtctool random_key`> p1=`pybtctool privtopub $k1`> p2=`pybtctool privtopub $k2`> p3=`pybtctool privtopub $k3`
Traceback (most recent call last):
  File "/usr/local/bin/pybtctool", line 4, in <module>
    __import__('pkg_resources').run_script('bitcoin==1.1.42', 'pybtctool')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1667, in run_script
    exec(code, namespace, namespace)
  File "/Library/Python/2.7/site-packages/bitcoin-1.1.42-py2.7.egg/EGG-INFO/scripts/pybtctool", line 32, in <module>
    o = vars()[cmd](*args, **kwargs)
TypeError: privkey_to_pubkey() takes exactly 1 argument (0 given)
Traceback (most recent call last):
  File "/usr/local/bin/pybtctool", line 4, in <module>
    __import__('pkg_resources').run_script('bitcoin==1.1.42', 'pybtctool')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1667, in run_script
    exec(code, namespace, namespace)
  File "/Library/Python/2.7/site-packages/bitcoin-1.1.42-py2.7.egg/EGG-INFO/scripts/pybtctool", line 32, in <module>
    o = vars()[cmd](*args, **kwargs)
TypeError: privkey_to_pubkey() takes exactly 1 argument (0 given)

**Comment by alenuyee** [comment]
> ```
> k1=`pybtctool random_key`> k2=`pybtctool random_key`> k3=`pybtctool random_key`> p1=`pybtctool privtopub $k1`> p2=`pybtctool privtopub $k2`> p3=`pybtctool privtopub $k3`
> Traceback (most recent call last):
>   File "/usr/local/bin/pybtctool", line 4, in <module>
>     __import__('pkg_resources').run_script('bitcoin==1.1.42', 'pybtctool')
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 742, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1667, in run_script
>     exec(code, namespace, namespace)
>   File "/Library/Python/2.7/site-packages/bitcoin-1.1.42-py2.7.egg/EGG-INFO/scripts/pybtctool", line 32, in <module>
>     o = vars()[cmd](*args, **kwargs)
> TypeError: privkey_to_pubkey() takes exactly 1 argument (0 given)
> Traceback (most recent call last):
>   File "/usr/local/bin/pybtctool", line 4, in <module>
>     __import__('pkg_resources').run_script('bitcoin==1.1.42', 'pybtctool')
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 742, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1667, in run_script
>     exec(code, namespace, namespace)
>   File "/Library/Python/2.7/site-packages/bitcoin-1.1.42-py2.7.egg/EGG-INFO/scripts/pybtctool", line 32, in <module>
>     o = vars()[cmd](*args, **kwargs)
> TypeError: privkey_to_pubkey() takes exactly 1 argument (0 given)
> ```
