### ISSUE TITLE
pushtx error

### ISSUE THREAD

**Issue by quinnoaj** [vbuterin/pybitcointools#189]
after constructing my code to push a transaction in to the network

I run `pushtx(txt)`

then I got this error:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/bitcoin-1.1.42-py2.7.egg/bitcoin/bci.py", line 311, in pushtx
    return f(*args)
  File "/usr/local/lib/python2.7/site-packages/bitcoin-1.1.42-py2.7.egg/bitcoin/bci.py", line 261, in bci_pushtx
    if not re.match('^[0-9a-fA-F]*$', tx):
  File "/usr/local/lib/python2.7/re.py", line 141, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or buffer
`

Could it be there are problems with the serialize values?

**Comment by primal100** [comment]
What type is mktx or mksend returning? In pytthon 2, mktx uses join so it should return a string.
