### ISSUE TITLE
cannot use pybtctool with python3

### ISSUE THREAD

**Issue by mfutech** [vbuterin/pybitcointools#191]
fails at the print statement, if corrected fails later, example:

```
> python C:\Progs\Python36\Scripts\pybtctool random_electrum_seed

Traceback (most recent call last):
  File "C:\Progs\Python36\Scripts\pybtctool", line 32, in <module>
    o = vars()[cmd](*args, **kwargs)
  File "C:\Progs\Python36\lib\site-packages\bitcoin\main.py", line 419, in random_electrum_seed
    + str(int(time.time() * 1000000))
TypeError: can't concat bytes to str
```

**Comment by WeeLonelySoul** [comment]
Tried using 'python2.7 fileName.py'? or just in gerneral another Python version?

**Comment by mfutech** [comment]
I do not have a Pyhton2.7 installed. Need to install one and tests.
I'll let you know.
