### ISSUE TITLE
merkle_prove AssertionError

### ISSUE THREAD

**Issue by ethers** [vbuterin/pybitcointools#74]
On 189fc6628aa8a795d04fa4b8fbfefc3e9bdae207 there is an assertion error with:
https://github.com/vbuterin/pybitcointools/blob/master/bitcoin/blocks.py#L41

```
>>> tx = 'fe305e1ed08212d76161d853222048eea1f34af42ea0e197896a269fbf8dc2e0'
>>> merkle_prove(tx)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bitcoin/composite.py", line 128, in merkle_prove
  File "bitcoin/blocks.py", line 41, in mk_merkle_proof
AssertionError
```

**Comment by ethers** [comment]
Fixed by f81a5fc186d16eee57f76e9519fe4c4123939701
